<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrNgbQo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrNgbQo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIrNgbQo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIrNgbQo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIrNgbQo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IrNgbQo',
    'container.build_id' => '1f843b07',
    'container.build_time' => 1566812555,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrNgbQo');
