<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU8O08cr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU8O08cr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU8O08cr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU8O08cr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU8O08cr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U8O08cr',
    'container.build_id' => '52fa42cd',
    'container.build_time' => 1566816950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU8O08cr');
